default:
  image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - Install
  - Lint
  - Format
  - Test
  - Build

dependencies-ui:
  interruptible: true
  stage: Install
  script:
    - yarn install

lint-ui:
  interruptible: true
  stage: Lint
  script:
    - yarn lint

format-ui:
  interruptible: true
  stage: Format
  script:
    - yarn format

unit-test-ui:
  interruptible: true
  stage: Test
  script:
    - yarn test

build-ui:
  interruptible: true
  stage: Build
  script:
    - yarn build
