default:
  image: node:latest

workflow:
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - when: always

cache:
  paths:
    - node_modules/

stages:
  - UI

install-dependencies-ui:
  interruptible: true
  stage: UI
  script:
    - yarn install

lint-ui:
  interruptible: true
  stage: UI
  script:
    - yarn lint

coverage-ui:
  interruptible: true
  stage: UI
  script:
    - yarn coverage

format-ui:
  interruptible: true
  stage: UI
  script:
    - yarn format

unit-test-ui:
  interruptible: true
  stage: UI
  script:
    - yarn test

build-ui:
  interruptible: true
  stage: UI
  script:
    - yarn build
