image: node:latest

stages:
  - install
  - test
  - build

install-dependencies:
  interruptible: true
  stage: install
  script:
    - yarn install

build-frontend:
  interruptible: true
  stage: build
  script:
    - yarn build

ui-component-test:
  interruptible: true
  stage: test
  script:
    - yarn test
