default:
  image: node:latest

workflow:
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - when: always

cache:
  paths:
    - node_modules/

stages:
  - Install
  - Lint
  - Coverage
  - Format
  - Test
  - Build

dependencies-ui:
  interruptible: true
  stage: Install
  script:
    - yarn install

lint-ui:
  interruptible: true
  stage: Lint
  script:
    - yarn lint

coverage-ui:
  interruptible: true
  stage: Coverage
  script:
    - yarn coveragte

format-ui:
  interruptible: true
  stage: Format
  script:
    - yarn format

unit-test-ui:
  interruptible: true
  stage: Test
  script:
    - yarn test

build-ui:
  interruptible: true
  stage: Build
  script:
    - yarn build
