default:
  image: node:latest

workflow:
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - when: always

cache:
  paths:
    - node_modules/

stages:
  - UI

build-lint-coverage-test-format:
  interruptible: true
  stage: UI
  script:
    - yarn install
    - yarn lint
    - yarn coverage
    - yarn format
    - yarn test
    - yarn build
  