version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: local_mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_RW_USER=$MYSQL_RW_USER
      - MYSQL_RW_USER_PASSWORD=$MYSQL_RW_USER_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
volumes:
  my-db: